### ISSUE TITLE
set current course

### ISSUE THREAD

**Issue by umutacar** [diderot-edu/diderot-cli#10]
it would be nice if `diderot` could be run like this:
```
(invoke diderot with my course)
$ diderot 15210    
this asks me to log in and sets my course by default this would be current semester
$ diderot Fall18 15210 
would do the same as above but would find the Fall18 edition
after the user logs on like this, they would not have to provide course label to the queries, which is a bit cumbersome. 
```

**Comment by rohany** [comment]
I can look into doing something like this -- how do we know what is the current semester of a course? Also, I was thinking that this could be an option -- you don't need to specify a course, but if you wanted to you could do something like

```
set_course 15210:S19
```

Then all the future commands would use that as a base, and you could change the course whenever you wanted to (if you happened to be using diderot for multiple courses).

**Comment by umutacar** [comment]
Yes.  that would work.
A small suggestion on that: we can think of courses and semesters as 'unix
directories' so you can have a command like this
```
cc 15210/s19
```
This would "change course" to 15210/s19.
You would then include in the Diderot CLI the current course just as in a
directory
```
Diderot--15210/s19 >
```


-- Umut

**Comment by rohany** [comment]
that is a great suggestion -- I think it would be doable as well. Is it possible to make the course labels be structured like that instead of 15210:S19?

**Comment by umutacar** [comment]
in principle, yes this is entirely possible. though it would also mean that
we would need to change some of the existing labels.  perhaps we should do
this.  @ada-anil found a bug in the current code though.  Anil, is this
fixable?

-- Umut

**Comment by rohany** [comment]
Done in #15 -- I've provided set_course and unset_course commands which have the desired behavior. 

I'll work on adding some aliases later, but that isn't a priority right now.

```
DiderotCLI >> set_course 15210:S19
Course set successfully.
DiderotCLI/15210:S19 >> list_assignments
ParenLab	SkylineLab	MCSSLab	BignumLab	RandomLab
DiderotCLI/15210:S19 >> download_assignment
usage: download_assignment [-h] homework
download_assignment: error: the following arguments are required: homework
```

**Comment by umutacar** [comment]
Süper!
