### ISSUE TITLE
CLI functionalities

### ISSUE THREAD

**Issue by iliano** [diderot-edu/diderot-cli#100]
As discussed with Umut, it would be great if the current revamp of the Diderot CLI supported the following functionalities: in the JSON file uploaded by **upload_upload** command, add fields for the release and due date of each chapter.

For example:
```
{
  "title" : "Programming Homeworks",
  "book" : "book:programming",

  "parts": [
    {
      "number": 1,
      "title": "Programming Homeworks",
      "label": "part:programming"
    }
  ],

  "chapters" : [
    {
      "part": 1,
      "number": 0,
      "title":        "Sample Assignment (UNGRADED)",
      "label":        "prog:sample",
      "release date": "Jan 13 2020, 9:00",
      "due date":     "Jan 13 2020, 17:30"
    },
    {
      "part": 1,
      "number": 1,
      "title": "Scavenger hunt",
      "label": "prog:scavhunt",
      "release date": "Jan 23 2020, 21:00",
      "due date":     "Jan 30 2020, 21:00"
    },
...
```
Ideally, it would be great if the JSON object supported fields for anything we can configure in a book (especially for exams).

**Comment by umutacar** [comment]
This is implemented in the new CLI.  There are some example files here
https://www.diderot.one/courses/15/books/46/chapter/3627#atom-502622
