### ISSUE TITLE
chapter uploads

### ISSUE THREAD

**Issue by umutacar** [diderot-edu/diderot-cli#11]
@rohany 

This (PR #8) is great!! 
I have a few suggestions for the command arguments.
Recall the command is
```
update_book <book label> <chapter label> [--pdf  [--video_url] | --slides  [--video_url] | --xml [--images] [--xml_pdf] ]
```

* `book label` isn't unique across courses.  so this CLI would not know which course to update.  perhaps change this so that it logs you onto a course, as I suggested in #10. 
* `chapter label` is not user friendly here because it will likely be a mambo jambo string maybe just include the number?

**Comment by rohany** [comment]
Oh i didn't know that, I thought the book label was unique. I can add a course field here / have a log into a course.

I agree the chapter label is a bit odd here, but I'm unsure of what other fields to specify of the chapter to ensure that the course->book->chapter link gives us exactly one chapter back.

**Comment by umutacar** [comment]
You can use the chapter number.  It is unique and will likely be easier to
work with for the user.

-- Umut

**Comment by rohany** [comment]
Is there another field I should be looking at? The chapter model says this about the chapter.number field.
```    
number = models.IntegerField(default=0) # Display number. For chapter, should be same as rank.
    # number is currently not being used!
```

**Comment by umutacar** [comment]
Yes, I believe we use "rank"

-- Umut

**Comment by rohany** [comment]
cc @ada-anil here -- when I discussed this with anil he suggested the label -- what is the best thing to do here?

**Comment by umutacar** [comment]
The problem with label is that it is not always known to the user, e.g., i can create a chapter with an auto-gen label and i don't know that it is.  (At least not easily). 
Happy to hear what Anil thinks.

**Comment by rohany** [comment]
yeah, another thing I ran into was that some xml file can change the label as well -- so using the same upload command can fail the next time.

**Comment by umutacar** [comment]
Yes, exactly.  Chapter labels are fickle.

-- Umut

**Comment by ada-anil** [comment]
I think the best would be to have chapter creation and upload done together. If you are going to create the chapter from the interface and then upload contents from terminal, you lose a lot of the benefit. 

Without getting into the details, it could be something like:

If you upload an xml chapter, you get the label and the title from the xml. If chapter already exits, you upload to that chapter. If not, create the chapter and upload the contents. (maybe require an optional rank parameter; if rank is not provided, and you need to generate it, get next available integer rank)

If you upload a pdf chapter, and you do not provide a label, create a new chapter with a new label and upload contents. If you provide a label, and matches an existing chapter, upload contents there. If the label does not match anything, create a new chapter with that label, and upload contents there.

Maybe this is too complicated? I don't know.

**Comment by ada-anil** [comment]
Note that in this scenario, if I am uploading the contents of a book from scratch, I would not need to provide any labels or ranks.

**Comment by umutacar** [comment]
Let's try to aim at something simple and orthogonal, that is, it treats
upload and create separately.  Otherwise it could get confusing.

The common use for this will be updating a created chapter, possibly after
creating the chapters in bulk, using json.  Users will create a chapter
once but will likely update many times.

My suggestion is to simply take the rank and upload.

We can add an mc command that creates an empty chapter.

**Comment by ada-anil** [comment]
I think rank is more fragile than label, you can accidentally hit a wrong key and give a wrong rank, uploading the contents to a wrong chapter. Ranks can also change from semester to semester, or even in the same semester. This is why I suggested using label. 

But in any case, I don't feel strongly about it. If you would like to use rank, that is totally fine with me.

**Comment by rohany** [comment]
We could include a create chapter command, which optionally allows you to specify things like the name, number etc. If a chapter that matches this info exists then it is a no op. The command can return the full information about the chapter which you would need to upload content to it later.

**Comment by rohany** [comment]
I think we want to avoid doing any sort of xml / pdf manipulation in the CLI, in order to avoid code duplication with diderot.

**Comment by umutacar** [comment]
I hardly ever change the rank of a chapter that I created.  (Consistency
across semesters seems like a second order issue to me.)

I agree that there could be errors but they are easy to correct by
reuploading.

One possibility is for the cli to fetch the title of the chapter and
confirm with the user and then proceed with the upload.

**Comment by umutacar** [comment]
Yes the cli can create a chapter from a given rank and title.  That would
be nice.  I don't think you need anything else.

(This would be analogous to mkdir of Unix.  You can call it mkcha if you
want).

**Comment by rohany** [comment]
Do we also need to specify a book version to update here?

**Comment by umutacar** [comment]
Course and book label uniquely identifies a book.  What did you mean by
"version"?

**Comment by rohany** [comment]
In the books model:
```
    class Meta:
        unique_together = ("course", "label", "version")
```

**Comment by rohany** [comment]
out of curiosity, why is the chapter rank a Decimal?

**Comment by ada-anil** [comment]
I think you can ignore the version for now. In the future we may have a versioning system.

There are several use cases but here is one: you want to create an addendum chapter for say chapter X. Then you can create chapter X.5 for that purpose. Generally, it gives you the flexibility to stick a new chapter anywhere you want (without shifting other chapters).

**Comment by umutacar** [comment]
Version is used for "archiving" books. This is currently not used.

**Comment by rohany** [comment]
Alright, #16 adds the following
* requiring a course in the arguments
* specifying chapters by rank (I included a list chapters command to make finding the rank easier)
* asking users for confirmation before continuing

I will work on a create chapter command next.

```
DiderotCLI >> update_book 15210:S19 TestBook2 1 --xml ~/Documents/diderot/lambdabricks/src/examples/iso-paper/iso.xml --images ~/Documents/diderot/lambdabricks/src/examples/iso-paper/media-iso/
Begin upload to Course: 15210:S19, Book: TestBook2, Chapter Number: 1, Chapter Title: Graph Isomorphism? Enter yes to proceed. Any other input will cancel the upload.
yes
Uploading file: graphs-for-matching-tree.png
Uploading file: optimized-plot.png
Uploading file: isomorphic-random-graphs-plot.png
Uploading file: bounded-degree-subgraphs-plot.png
Uploading file: all-self-speedups-plot.png
Uploading file: split-diagram-pre.png
Uploading file: 4d-mesh-subgraphs-plot.png
Uploading file: matching-tree.png
Uploading file: comparison-on-cv-plot.png
Uploading file: isomorphic-meshes-plot.png
Uploading file: split-diagram-post.png
Uploading file: 2d-mesh-subgraphs-plot.png
Uploading file: random-subgraphs-plot.png
Waiting for book upload to complete...
Waiting for book upload to complete...
Waiting for book upload to complete...
Waiting for book upload to complete...
Waiting for book upload to complete...
Waiting for book upload to complete...
Beaming completed, but there were some issues:
Label: fig:speedup-random is undefined
Label: fig:speedup-mesh-subgraph is undefined
Label: fig:speedup-mesh-fullgraph is undefined
Label: fig:speedup-random is undefined
Label: fig:speedup-mesh-subgraph is undefined
Label: fig:speedup-mesh-fullgraph is undefined
Book uploaded successfully.
DiderotCLI >>
```

**Comment by rohany** [comment]
A create chapter command has now been added to the CLI via #17 

I'll close this issue now, since all parts have been addressed.

```
DiderotCLI >> create_chapter 15210:S19 TestBook2 --part 1 --number 3 --title Test --label TESTINGLABELROHANY
Successfully created chapter.
```
