### ISSUE TITLE
Add some nice aliases.

### ISSUE THREAD

**Issue by rohany** [diderot-edu/diderot-cli#18]
Umut suggested a few aliases, such as cc -> set_course, mc -> make chapter etc. Set up a framework for easily handling aliases.

**Comment by umutacar** [comment]
Would also be nice to see the current course on the command line.

**Comment by rohany** [comment]
That is already implemented

**Comment by umutacar** [comment]
Great!  I missed that somehow.

-- Umut

**Comment by rohany** [comment]
This is no longer applicable.
