### ISSUE TITLE
CLI guide

### ISSUE THREAD

**Issue by umutacar** [diderot-edu/diderot-cli#19]
A very basic guide to CLI would be helpful.  Add this as a separate chapter in the repo `guide`

As a stub, I created cli/cli.tex, and put in an outline.

Makefile should work.

**Comment by rohany** [comment]
Should we just have a separate document (cli_admin.tex) for documenting admin features?

**Comment by rohany** [comment]
Never mind, i see what you have set up.

**Comment by rohany** [comment]
I don't have permissions to push to the `guide` repo -- when you add me I can push the documentation.

**Comment by umutacar** [comment]
I's say just one file should suffice. One section for shared features one
for the admin.  I thought I committed a (basic) outline did I forget to
push.

**Comment by umutacar** [comment]
Ok.

**Comment by umutacar** [comment]
Ok just did.  I thought by default anyone could send a PR.  I shall look
into that.

**Comment by rohany** [comment]
Based on feedback from iliano, this needs quite a bit of work. I will to add more detailed documentation to each command, instead of having more information actually be in the CLI.

**Comment by rohany** [comment]
Will students be able to access the guide? If not, where do we intend on putting the CLI documentation for the student version?

**Comment by umutacar** [comment]
Yes the guide is public so they can access it.  That would be the right
place for the CLI documentation.
