### ISSUE TITLE
no parts for booklets

### ISSUE THREAD

**Issue by umutacar** [diderot-edu/diderot-cli#21]
Diderot distinguishes between two kinds of books, those with & without parts.  The latter are called booklets.  Most people will use these.  The create chapter currently seems to require a part even if the book is a booklet.  See below

```
create_chapter --number 15 --title 'Chapter from CLI' BAL
create_chapter --number 15 --title 'Chapter from CLI' BAL
usage: create_chapter [-h] --part PART --number NUMBER [--title TITLE]
                      [--label LABEL]
                      book
create_chapter: error: the following arguments are required: --part
```

**Comment by rohany** [comment]
The create_chapter endpoint for book creation seems to require a part primary key. If the book is a booklet, what should that be?

**Comment by rohany** [comment]
@ada-anil might know the answer here as well

**Comment by umutacar** [comment]
For a booklet, the part of a chapter will be set to Null.  Does the
endpoint allow far that?


-- Umut

**Comment by rohany** [comment]
![image](https://user-images.githubusercontent.com/15331872/63173820-aada0200-c00e-11e9-8f13-bab7b8dcd310.png)

No it seems like it expects something else

**Comment by umutacar** [comment]
yeap, it doesn't need to require it and shouldn't.  That function could check book/booklet and if the book is a booklet, then it would not require the part_pk.  Not sure who wrote the function.  @ada-anil do you know?

**Comment by rohany** [comment]
Ok, once that update gets merged I'll fix this component of the CLI. It is a simple fix on my end.

**Comment by ada-anil** [comment]
That is not how it is organized. It is assumed that a book consists of parts, and parts consists of chapters. This does not change for a book vs booklet. The only difference is that in a booklet, there is only one part (which is invisible to the user), and you cannot create new parts.

**Comment by rohany** [comment]
Is the default part number 1 then? Or 0?

**Comment by ada-anil** [comment]
the rank is 1, and the label is book.label + '-part1'.

**Comment by umutacar** [comment]
Rohan still good to keep the isbooklet in the API.  This way of doing
things will be implementation dependent so will likely revise this down the
road.

**Comment by umutacar** [comment]
While you are at it, you might request the API to pass out the label of the
unique part for booklets.  That is a reasonable fix for this and breaks the
implementation dependency.

**Comment by rohany** [comment]
I just put up a pr getting booklet information about a book — everything else can be handled with existing information.

**Comment by umutacar** [comment]
Saw that PR.  it looks good but it is not good hardwire the way that the
label is constructed (for the unique part).   If the Diderot implementation
changes, the CLI will break.  So add another field requesting the only
part's label (relevant only for booklet's).  You can tall is "host_part".

-- Umut

**Comment by rohany** [comment]
I can filter on parts by the book primary key— if we have a booklet I filter parts by the target books pk to get back the pk of the only part of that book

**Comment by umutacar** [comment]
Good idea!!
