### ISSUE TITLE
create chapter title

### ISSUE THREAD

**Issue by umutacar** [diderot-edu/diderot-cli#23]
Should the title be a string?  I wasn't able to create a chapter with a title like this "Chapter from CLI"
For this command, displaying an example would help.

**Comment by rohany** [comment]
Done in #25.

This is quite annoying -- the CLI package that python provides handles string input differently than bash -- I expected quotes to work, but they dont. I updated the help message to give an example.

If you wanted that title, you would use '--title Chapter From CLI'

**Comment by rohany** [comment]
Actually i found something to make this easier -- i will fix this again to try and have the same quote semantics as bash

**Comment by rohany** [comment]
Done -- bash like quote semantics should work everywhere now.
