### ISSUE TITLE
update_book command

### ISSUE THREAD

**Issue by umutacar** [diderot-edu/diderot-cli#24]
- [x] change the name to `upload_chapter'

- [x] Change `images` --> `attach`
We migth want to attach anything.  I don't recall how this works, but it would be best if it took a directory and took everything within that directory (also recursively) and uploaded onto diderot (as a list of files), e.g., 
dirA/fileA.png
dirA/dirAA/fileAA.jpg

would upload both files fileA.png and fileAA.png.

- [ ] There seems to be something wrong with image uploads see below.  If I don't supply the --images directory than it works.  
```
DiderotCLI/15210:S19 >> update_book --xml ~/diderot/15897/lambda/lambda.xml --images ~/diderot/15897/lambda
update_book --xml ~/diderot/15897/lambda/lambda.xml --images ~/diderot/15897/lambda
usage: update_book [-h] [--pdf PDF] [--slides SLIDES] [--video_url VIDEO_URL]
                   [--xml XML] [--images IMAGES [IMAGES ...]]
                   [--xml_pdf XML_PDF]
                   book chapter
update_book: error: the following arguments are required: book, chapter
DiderotCLI/15210:S19 >> update_book --xml ~/diderot/15897/lambda/lambda.xml --images ~/diderot/15897/lambda TB 61
update_book --xml ~/diderot/15897/lambda/lambda.xml --images ~/diderot/15897/lambda TB 61
usage: update_book [-h] [--pdf PDF] [--slides SLIDES] [--video_url VIDEO_URL]
                   [--xml XML] [--images IMAGES [IMAGES ...]]
                   [--xml_pdf XML_PDF]
                   book chapter
update_book: error: the following arguments are required: book, chapter
DiderotCLI/15210:S19 >> update_book --xml ~/diderot/15897/lambda/lambda.xml TB 61
update_book --xml ~/diderot/15897/lambda/lambda.xml TB 61
Begin upload to Course: 15210:S19, Book: TB, Chapter Number: 61, Chapter Title: CLI-CHAPTER? Enter yes to proceed. Any other input will cancel the upload.
yes
yes
Waiting for book upload to complete...
```

**Comment by rohany** [comment]
Ok, i will rename images to attach.

As for use, only use the --images/--attach flag once, and pass in the list of directories after it.

Try this

```
update_book TB 61 --xml ~/diderot/15897/lambda/lambda.xml --images ~/diderot/15897/lambda 
```

I think the issue with above is that the parser thought that TB and 61 were pare of the images argument, rather than the book and input number. Let me try and make it clearer in the help that book and chapter need to come first.

**Comment by umutacar** [comment]
ok, makes sense.

-- Umut

**Comment by rohany** [comment]
Alright, i added a custom formatter to argparse which will now properly show that positional arguments (course, book, etc.) need to go before optional arguments to avoid this issue.
