### ISSUE TITLE
Should this be a embedded console?

### ISSUE THREAD

**Issue by rohany** [diderot-edu/diderot-cli#32]
Discussion with iliano has brought up a good question -- should this actually be an embedded console? If it is more useful to just run individual commands, then perhaps we should just have a true CLI instead.

I believe we should collect some feedback from both students and administrators before making a full decision.

**Comment by rohany** [comment]
I imagine this is actually not that hard to do, it wouldn't change much to fix this actually.

**Comment by rohany** [comment]
I take it back, it would take a decent refactor to do this. In order to do this correctly, take a look at argparse's subparsers -- https://pymotw.com/3/argparse/

**Comment by rohany** [comment]
Another thing to do is look into the packages click or fire. The downside of these is that they aren't part of the standard library, so they require some installation.

**Comment by rohany** [comment]
The more I think about this, the more I agree with iliano. An embedded console isn't really usable, especially for scripting purposes, which was the original goal of the CLI.

**Comment by umutacar** [comment]
I see a lot of advantages to the 'interpreter" or embedded console.  It acts a bit like programming language interpreter, which is useful to get small things done.  But sometimes we want to run a program.  To support this the cli could take a program/script as a sequence of commands and run it line by line.  For example, the program could set the course and upload a bunch of chapters one by one.  It could be invoked by 
"Diderot --exec myscrioot.did"

**Comment by rohany** [comment]
I added a flag to the CLI right now that lets it execute commands without entering the console and that seems useful to iliano right now. 

It seems like even if you were to do a small task you could do so without being in a console -- you would just want to run the task that you needed (ie submitting a homework, or uploading a chapter). Needing to enter the console instead of a one line terminal command seems like overkill.

**Comment by umutacar** [comment]
Ok great.  This is probably good enough for now.  A true cli example would
be the aws cli.  The way it works as I understand it is by using
private/public keys.  That might be the right way to do this but would
require a bit more work to allow users to generate them on diderot etc...

**Comment by rohany** [comment]
Some feedback

Gaurav -- 
```
It's really not worth the trouble in implementing any sort of CLI. Everyone has their own shell set up exactly as they like, its much better if we can just run commands (where the command runner does not have any transient state; i.e. one command -> one change on the server).

Also, I noticed that every operation I perform involves uploading and/or downloading a chunk of data, and so costs much more than the overhead from logging in to the server. This means you don't even need to implement link persistence.

I'm currently using it exactly like that by just directing in to stdin all the commands I want to run; the EOF automatically terminates the script.

What would be helpful instead is (1) removing the select_course construction and requiring all commands to specify a course, and (2) deployment keys separate from a password, which will let us audit separate access and (eventually, when implemented) restrict permissions to reading and writing individual parts of the course.

Thanks!
```

Iliano -- 
```
Sounds good. In fact, would anyone have a need for an embedded shell?  Think about how package management tools work in any OS: one command with a bunch of options. 
```


That being said, I'm already well in the way of implementing a standalone version of the CLI. I can reuse a large amount of the code and am rewriting some parts in a much better way.
