### ISSUE TITLE
Logged in vs Logged out

### ISSUE THREAD

**Issue by rohany** [diderot-edu/diderot-cli#34]
The api_calls.py right now is littered with logic that checks if a user is logged in or not. This doesn't seem important right now, so we should remove it.

**Comment by umutacar** [comment]
One possibility would be to enforce authentication at each API call.  It should be possible to factor this out into its own function and reduce it to a single line.  This is going to cost a bit but I would expect it to be a small inconvenience.

**Comment by rohany** [comment]
Yes it is already like that (we log in at the beginning of the session). It’s some boilerplate logic left over from when I ported over wills code
