### ISSUE TITLE
Better solution than always looking in the same place for credentials

### ISSUE THREAD

**Issue by rohany** [diderot-edu/diderot-cli#50]
Umut brought up a good point, that if we always look ~/.diderot/credentials, then that will encourage students to store their passwords in that location. However, that location by default is not private on AFS, and it could lead to students seeing other student's passwords. We need a way to work around this.

**Comment by rohany** [comment]
One solution is to use environment variables -- we could have an environment variable pointing to a file to look at for credentials. This feels more like a bandaid solution however.

**Comment by gauravmm** [comment]
Storing them in ` ~/.diderot/credentials` is fine. I suggest you do do what `ssh` does with `~/.ssh/id_*`: only read the file if it the permissions are `0600`.

**Comment by rohany** [comment]
If i understand correctly, does 0600 just mean that only the owner of the file can read it? ie no other AFS users other than the creator can read it?

If so, that is a good idea.

**Comment by gauravmm** [comment]
Yes. `0400` is "only I can read" and `0200` is "only I can write". (Note the leading `0`: it means the number is in octal.)

**Comment by rohany** [comment]
Hi Gaurav, can I ask you to review this PR -- https://github.com/diderot-edu/diderot-cli/pull/54? Thanks alot!
