### ISSUE TITLE
Diderot website should have an empty public repo to collect issues. 

### ISSUE THREAD

**Issue by gauravmm** [diderot-edu/diderot-cli#58]
I have some issues/improvements I want to report, including:

- Center-clicking on notes in the notifications should open the particular notification in a new tab; it just takes you to the post office.
- Ctrl+enter should post-and-close open responses. (Perhaps Ctrl+shift+enter can post-and-open responses?)
- When posting an annoucement, I get an email even if I uncheck the "send an email" option.

**Comment by rohany** [comment]
We ended up creating this -- i think all these open issues are on there?
