### ISSUE TITLE
label

### ISSUE THREAD

**Issue by umutacar** [diderot-edu/diderot-cli#61]
our new course labels include spaces commas etc. this leads to an error
```
make list_chapters
/Users/umut/diderot/diderot-cli/diderot_admin list_chapters "CMU:Pittsburgh, PA:15210:Spring:2019-20" "TB"
Invalid input course label.
Error listing chapters.
make: *** [list_chapters] Error 1
bash-3.2$ 
```

**Comment by rohany** [comment]
Which diderot instance are you running this against? Locally courses with commas and spaces in their label work for me.

**Comment by umutacar** [comment]
we figured out that one possibility is that i didn't have access to that course (as an instructor).  it would be good if the error message says that "you might not have access rights to this course."

**Comment by umutacar** [comment]
confirmed that the issue was access rights.  just updating the error message would suffice.

**Comment by rohany** [comment]
Ok closing this, since I merged a pr that updates the error message.
