### ISSUE TITLE
book and booklet uploads

### ISSUE THREAD

**Issue by umutacar** [diderot-edu/diderot-cli#69]
allow booklet  and book to be specified as a json file and be created and uploaded wholesale

```
{book: exam/,
 title: Exam 1,
 label: EXAM1,
    chapter : {
      xml: truefalse/truefalse.xml, 
      pdf: truefalse/truefalse.pdf
     }
    chapter: {
      xml: shortanswers/shortanswers.xml, 
      attachments: shortanswers/media,
     pdf: hortanswers/shortanswers.pdf
     },
    chapter {
       xml: dfs/dfs.xml, 
      attachemnts: dfs/media, 
      pdf: dfs/dfs.pdf
    }
}
```

```
{book: exam/,
 title: Exam 1,
 label: EXAM1
 part 1: { 
    label: part:truefalse,    
    title:  True-False Problems,
    chapter : {
      xml: truefalse/truefalse_version1.xml, 
      pdf: truefalse/truefalse_version1.pdf
     }
    chapter : {
      xml: truefalse/truefalse_version2.xml, 
      pdf: truefalse/truefalse_version2.pdf
     }
  },
  part 2: {
    label: part:shortanswers,
    title: Short Answers,
    chapter: {
      xml: shortanswers/shortanswers_version1.xml, 
      attachments: shortanswers/media_version1,
     pdf: hortanswers/shortanswers_version1.pdf
     },
    chapter: {
      xml: shortanswers/shortanswers_version2.xml, 
      attachments: shortanswers/media_version2,
     pdf: hortanswers/shortanswers_version2.pdf
     }
  } 
  part 3: {
    label: part:dfs,
    title: Depth First Search
    chapter {
       xml: dfs/dfs.xml, 
      attachemnts: dfs/media, 
      pdf: dfs/dfs.pdf
    }
  }
}
```

**Comment by rohany** [comment]
This needs to be updated slightly, it's missing some information and isn't actually JSON.

The chapters need either a number or label, and will be formatted like:

```
[
  {
     "course": "<course label>",
     "book" : "<book label>",
     "chapters": [
        {
          "label" : "<chapter label>",
          "number": "<chapter number (one of label or number is needed)>",
          "xml": "<path to xml>",
          "pdf": "<path to pdf>",
          "attachments": ["<path to attachment 1>", "<path to attachment 2>"],
        },
        {
           <chapter definition 2>
        },
      ]
   }
]
```

**Comment by rohany** [comment]
Should this automatically create chapters if they do not exist?

**Comment by umutacar** [comment]
yeap, it should.  if they exist, it would simply overwrite (reupload into)
them.

-- Umut

**Comment by umutacar** [comment]
re: labels, there is no need for them (they are in the xml).
re: numbers: this is implicit in the order, the first in the list is the
first chapter, etc.  so this way it is easy to reorder them if needed.

-- Umut

**Comment by rohany** [comment]
Ok, we can omit the label. However, I think we should require numbers, because not having numbers means that you must have all chapter uploads in this bulk uploader. It makes sense for users to use this without having to put all the chapters in this upload file.

**Comment by umutacar** [comment]
that is a good point.  maybe we can get the best of both worlds, if a
chapter has a number, then use it, if not, then give it that of the
previous + 1 (note that of the previous could  be autogenerated).  so
if no numbers age given, then they would be sequentially numbered.

-- Umut

**Comment by rohany** [comment]
Hmm. I think I will start with requiring numbers (for simplicity), and can do that after.

**Comment by umutacar** [comment]
yeap sounds good.  once you get that working, it should be easy to iterate
over the iterate/fold over the chapters and assign them numbers as
suggested.

-- Umut
