### ISSUE TITLE
chapter uploads

### ISSUE THREAD

**Issue by umutacar** [diderot-edu/diderot-cli#8]
I recall that we talked about this but I am not sure if it has been implemented.  It would be nice to allow instructors and TA's to upload chapters like this
```
$ did upload -book <book label> -chapter <chapter number> -attach path/to/attachments path/to/chapter/main.[xml | pdf]
```

Once invoked, this command could terminate immediately, but it would be better if it "spun" its wheels, e.g., by printing a "." every 1 seconds or so and then take the return value from the chapter upload and print it.  

This requires some coordination between the book uploads API.  Perhaps the trickiest part is that it would have to construct a request object with file attachments (e.g., typically some image files).

How much work would this require?

**Comment by rohany** [comment]
I doubt it would be that much work, given that the views on the diderot side do alot of work -- for context you can see here how much code it took to do file uploads for autograder.tar, autograde-Makefile etc for codehomeworks.

https://github.com/diderot-edu/diderot-cli/blob/7a8fdb1321f83fb690fd88789236ec2ff1566a59/api_calls.py#L163

**Comment by umutacar** [comment]
That is great. In that case, it would be add this feature to the admin cli.

**Comment by rohany** [comment]
do you want to do this, or should I? If I am to do it, what are the appropriate endpoints to look at in books?

**Comment by rohany** [comment]
Anil says look at --  diderot/apps/books/views.py

**Comment by rohany** [comment]
I should just be able to post, calling the method Books/add_content_to_chapter right?

**Comment by ada-anil** [comment]
Yeah. You have to make sure request is loaded properly (in particular request.POST and request.FILES).

**Comment by rohany** [comment]
Can i also get some example xml / mlx etc files to try and upload? Is there a repo of these?

**Comment by ada-anil** [comment]
I think there is some in src/examples (in lambdabricks)

**Comment by umutacar** [comment]
I put one under src/examples/genome  it also includes the media files.


-- Umut

**Comment by rohany** [comment]
What is the difference between the attachment here, and the path/to/chapter/main ?

**Comment by rohany** [comment]
never mind -- I think i got it. If we upload an XML file, we also need to upload all the images that that are linked in the file. Are all the images that are linked assumed to not be inside any folders? Like if within the XML there is a photo "image.png", this is not going to be relative to some path?

**Comment by rohany** [comment]
To be clear -- say the user passes in upload ... images/in/this/folder/* and within this folder are images img1.jpg and img2.jpg -- do I need to upload these images as images/in/this/folder/img1.jpn etc or img1.jpg? could there be naming collisions in the folder?

**Comment by ada-anil** [comment]
You can leave out the path for the images. Only the file name (without the path) is used.

**Comment by rohany** [comment]
Side note -- do chapter numbers shift up if another is inserted with an existing number? It seems like you have to preallocate how many chapters you have in a part. What happens if you end up needing more chapters?

**Comment by ada-anil** [comment]
There are two stages to creating a chapter. First you create the chapter by providing details like title, label, number etc (perhaps this corresponds to what you refer to as preallocation). Then after that, you upload content into the chapter. I thought you were doing the second part only. Are you doing both?

**Comment by rohany** [comment]
No I’m just doing uploads right now. I was wondering because I was making a new chapter in the ui to test

**Comment by ada-anil** [comment]
I see. It should give you an error if you try to use a number that has already been taken.

**Comment by ada-anil** [comment]
But this is a recent change, so it is possible it is on the version branch, but not yet on master.

**Comment by ada-anil** [comment]
Also, there is no rule on what chapter numbers a part can contain. So part 1 can have chapter 10 and part 2 can have chapter 1. We leave that to the author.

**Comment by rohany** [comment]
What field in the chapter model does the number displayed correspond to -- the chapter model says "number" is currently unused.

**Comment by ada-anil** [comment]
rank

Do you need that info though? I don't think it is relevant for adding content to an existing chapter.

**Comment by rohany** [comment]
I need to get the chapter pk to pass into the post — I was planning on getting it by letting user pass in a chapter number and figure out the pk from thaf

**Comment by ada-anil** [comment]
I think doing this by label would be the best. Label is meant to be used as a unique identifier.

**Comment by ada-anil** [comment]
And it would make errors (uploading contents to a wrong chapter) less likely.

**Comment by rohany** [comment]
I'm seeing this error in the logs when uploading the genome.xml file -- 

Error: Fatal error, multiply defined labels:
Label: alg:genome::alg::greedySS is multiply defined.
Label: def:genome::prob::overlap is multiply defined.

Is there something wrong with the example?

**Comment by ada-anil** [comment]
Does the book you are uploading to have other chapters? If so, they perhaps contain atoms with these labels. Maybe try uploading the chapter into a new book with no other chapters.

**Comment by umutacar** [comment]
The chapter isn't already in the book right?

**Comment by rohany** [comment]
With a new chapter, i see an error "Fatal Error: This upload deletes live blocks."

**Comment by rohany** [comment]
As of now though, the CLI works for slide + pdf uploads.

**Comment by ada-anil** [comment]
If you reupload content into an already released chapter, it can give that kind of Fatal Error because we do not allow released atoms to be deleted. If you upload it to an unreleased chapter, then it should be ok.

**Comment by rohany** [comment]
Ok, that worked. Thanks! How can I tell whether an upload succeeded or not / see these error messages without using cloudwatch?

**Comment by ada-anil** [comment]
The message gets stored in chapter.upload_warnings field (in the branch I'm working on now, there is also chapter.upload_errors to distinguish warnings and errors). What is a good way to access those fields from your side?

**Comment by rohany** [comment]
We can expose an API endpoint for it (can basically directly access models from the CLI). Once the base is ready I'll open a PR and show where we can add it.

**Comment by rohany** [comment]
I've been looking at this for a while and don't know the answer -- how you send a list of files in the request.FILES object? It seems like the html <multiple> input keyword handles this from the front end, but I'm not able to construct an http request from python (using the requests library) that actually has a list of files under a single key. Do you know how to do this?

**Comment by ada-anil** [comment]
The way we get, say images, is to do:
files = request.FILES.getlist('image')

There seems to be a setlist method, so I would suspect that you would use that:
https://docs.djangoproject.com/en/2.2/ref/request-response/#id1

**Comment by rohany** [comment]
Alright, I was able to figure it out. The chapter uploader CLI works now! Use it as follows -- 

```
update_book <book label> <chapter label> [--pdf  [--video_url] | --slides  [--video_url] | --xml [--images] [--xml_pdf] ]
```

**Comment by ada-anil** [comment]
Does it get all the images in a folder (even if they are in subfolders)?

**Comment by rohany** [comment]
Right now no, but it accepts globs. I can update it to additionally recursively traverse a folder though.

**Comment by ada-anil** [comment]
Yes, let's recursively traverse the folder. 

Soon we are going to support attachments other than images. In this case, we'll change the form field name from 'image' to 'attachments'. From the users side, they may divide their attachments up into two subfolders like 'images' and 'other_attachments'.

**Comment by rohany** [comment]
Ok, this is done. I think UX is a little rough around the edges (error messages aren't great), but it should be usable by iliano. Let me know if you think anything else should be added. Additionally, we will probably have to coordinate when you change how chapters are uploaded.
