### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by umutacar** [diderot-edu/diderot-cli#9]
can't seem to find course and list courses
bash-3.2$ ./diderot 
Username: diderot
Password: 
Successfully logged in to Diderot.
DiderotCLI >> list_assignments 15210:S19
list_assignments 15210:S19
Invalid input course label.
Error retrieving all assignments.
DiderotCLI >> list_assignments 15210:S19
list_assignments 15210:S19
Invalid input course label.
Error retrieving all assignments.
DiderotCLI >> list_courses
list_courses
Unable to make a request to Diderot.
Error retrieving all courses.

**Comment by rohany** [comment]
The recent updates to apis need to be deployed into Diderot to see an effect. The Cli defaults to Diderot.one, but if you give it an argument (like the address to your devserver) it will connect there.

**Comment by rohany** [comment]
I can push a change to this in a bit, but it also might be that I accidentally defaulted to http://www.diderot.one instead of https. Try that as well.

**Comment by rohany** [comment]
Yeah, i just checked, I don't think the API has been deployed on diderot right now.

Try deploying current master onto your devserver and trying

`./diderot http://<your devserver>`

**Comment by umutacar** [comment]
ok.  thanks!

-- Umut
